import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    appTitle: 'Farm2Home',
    tagline: 'Fresh produce directly from farmers to your doorstep',
    selectRole: 'Select your role to continue',
    farmerRole: 'Farmer',
    farmerDesc: 'Sell harvested produce directly at fair market prices with instant payouts.',
    customerRole: 'Customer',
    customerDesc: 'Browse farm-fresh organic produce with complete transparency on origin.',
    deliveryRole: 'Delivery Agent',
    deliveryDesc: 'Accept delivery tasks nearby, optimize routes, and earn steady income.',
    adminPortal: 'Admin Portal',
    welcomeBack: 'Welcome back',
    earningsThisMonth: 'Earnings this month',
    activeOrders: 'Active orders',
    lowStockAlert: 'Low-stock alert',
    quickActions: 'Quick actions',
    addProduct: 'Add product',
    updatePrice: 'Update price',
    updateStock: 'Update stock',
    viewOrders: 'View orders',
    myProducts: 'My products',
    stockStatus: 'Stock status',
    currentPrice: 'Current price',
    editPrice: 'Edit price',
    inStock: 'In stock',
    lowStock: 'Low stock',
    outOfStock: 'Out of stock',
    aiPriceHint: 'AI suggests ₹{price}',
    login: 'Login',
    register: 'Register',
    phoneOrEmail: 'Phone number or email',
    password: 'Password',
    otp: 'OTP (Use 1234 for demo)',
    sendOtp: 'Send OTP',
    verifyLogin: 'Verify & Login',
    // Auth redesign keys
    continueWithGoogle: 'Continue with Google',
    orSignInWith: 'or sign in with',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    sendResetLink: 'Send reset link',
    resetLinkSent: 'Check your email',
    resetLinkSentDesc: "If an account exists for that email address, we've sent a password reset link. Check your inbox (and spam folder).",
    backToLogin: 'Back to login',
    enterEmailForReset: "Enter your email address and we'll send you a link to reset your password.",
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    resetPassword: 'Reset password',
    passwordStrengthWeak: 'Weak',
    passwordStrengthFair: 'Fair',
    passwordStrengthGood: 'Good',
    passwordStrengthStrong: 'Strong',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 8 characters',
    passwordResetSuccess: 'Password reset! You can now sign in with your new password.',
    invalidResetToken: 'This reset link is invalid or has expired. Please request a new one.',
    resendOtp: 'Resend OTP',
    resendIn: 'Resend in',
    otpAutoAdvance: 'Enter one digit per box',
    mobileNumber: 'Mobile number',
    invalidMobile: 'Enter a valid 10-digit mobile number',
    googleAuthOnly: 'This account uses Google Sign-in. Please use the "Continue with Google" button.',
    googleRoleMismatch: 'This Google account is registered under a different role.',
    completeProfile: 'Complete your profile',
    completeProfileDesc: 'Just a few more details to get you started.',
    completeProfileSave: 'Save & continue to dashboard',
    farmName: 'Farm / village name',
    farmLocation: 'District & state',
    deliveryAddress: 'Delivery address',
    vehicleNumber: 'Vehicle registration number',
    farmerLoginHeadline: 'Sell direct. Keep more of what you earn.',
    farmerLoginSubline: 'List your produce, set your own price, reach customers without middlemen.',
    customerLoginHeadline: 'Fresh from the farm, straight to your home.',
    customerLoginSubline: 'Real produce from real farmers — no middlemen, no markups.',
    deliveryLoginHeadline: 'Drive the last mile that matters.',
    deliveryLoginSubline: 'Pick up from farms, deliver fresh, get paid on time.',
    trustFarmers: '500+ farmers',
    trustMiddlemen: 'Zero middlemen',
    trustFresh: 'Fresh within 24 hrs',
    authErrorIncorrect: 'Incorrect email or password. Please try again.',
    authErrorGeneric: 'Something went wrong. Please try again.',
    emailAddress: 'Email address',
    signingIn: 'Signing in…',
    sending: 'Sending…',
    resetting: 'Resetting…',
    saving: 'Saving…',
    searchPlaceholder: 'Search fresh vegetables, fruits, grains, or farmers...',
    addToCart: 'Add to cart',
    onDuty: 'On duty',
    offDuty: 'Off duty',
    totalDeliveries: 'Total deliveries today',
    completedSoFar: 'Completed so far',
    pickup: 'Pickup',
    drop: 'Drop',
    acceptJob: 'Accept delivery',
    markPickedUp: 'Mark picked up',
    outForDelivery: 'Out for delivery',
    markDelivered: 'Mark delivered',
    upcomingJobs: 'Upcoming deliveries',
    home: 'Home',
    route: 'Route',
    history: 'History',
    profile: 'Profile',
    // Analytics
    analytics: 'Analytics',
    analyticsTitle: 'Farmer Sales & Revenue Analytics',
    analyticsSubtitle: 'Track your real sales trend, top-selling produce, and harvest performance',
    totalRevenue: 'Total Lifetime Revenue',
    totalOrders: 'Total Orders',
    unitsSold: 'Total Units Sold',
    avgOrderValue: 'Average Order Value',
    revenueTrend: 'Revenue Trend',
    topProducts: 'Top Selling Produce',
    categorySplit: 'Category Breakdown',
    inventoryHealth: 'Inventory Health',
    noSalesYet: 'No sales data yet — your analytics will appear here once you receive orders.',
    days7: '7 Days',
    days30: '30 Days',
    months6: '6 Months',
    // AI Assistant
    aiAssistant: 'AI assistant',
    aiAssistantTitle: 'Farm2Home AI Assistant & Advisor',
    aiAssistantSubtitle: 'Direct farm pricing advice, inventory checks, and multi-language support',
    typeMessagePlaceholder: 'Ask a question (e.g. Which products are running low?)...',
    assistantTyping: 'Assistant is typing...',
    promptLowStock: 'Which products are low on stock?',
    promptPriceHelp: 'How do I update my price?',
    promptBestSeller: 'What sold best recently?',
    promptOrders: 'Show my recent orders',
    aiError: "Couldn't reach the assistant — please try again.",
    applyAiAction: 'Apply Recommendation',
    // Earnings & Payouts
    earnings: 'Earnings',
    earningsTitle: 'Farmer Earnings & Payouts',
    earningsSubtitle: 'Direct bank settlement ledger and revenue transaction records',
    lifetimeEarnings: 'Lifetime Earnings',
    pendingBalance: 'Pending Balance',
    paidOutAmount: 'Paid Out to Date',
    requestPayout: 'Request Payout',
    payoutDestination: 'Payout Destination',
    editDestination: 'Edit Details',
    minPayoutNotice: 'Minimum settlement payout request is ₹500',
    transactionsTitle: 'Earnings Ledger (Order Transactions)',
    orderNumber: 'Order #',
    date: 'Date',
    customer: 'Customer',
    items: 'Produce Items',
    gross: 'Gross',
    platformFee: 'Platform Fee (0%)',
    net: 'Net Payout',
    status: 'Status',
    filterAll: 'All Statuses',
    filterPending: 'Pending Settlement',
    filterPaid: 'Paid Out',
    payoutHistory: 'Payout History',
    noTransactionsYet: 'No earning transactions yet. Your confirmed orders will reflect here automatically.'
  },
  ta: {
    appTitle: 'Farm2Home (பண்ணை2வீடு)',
    tagline: 'விவசாயிகளிடமிருந்து நேரடியாக புதிய விளைபொருட்கள்',
    selectRole: 'தொடர உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்',
    farmerRole: 'விவசாயி',
    farmerDesc: 'இடைத்தரகர் இல்லாமல் நியாயமான விலையில் நேரடியாக விற்கவும்.',
    customerRole: 'வாடிக்கையாளர்',
    customerDesc: 'பண்ணையிலிருந்து நேரடியாக புதிய காய்கறிகளை வாங்கவும்.',
    deliveryRole: 'டெலிவரி முகவர்',
    deliveryDesc: 'டெலிவரி பணிகளை ஏற்று நிலையான வருமானம் பெறவும்.',
    adminPortal: 'நிர்வாக தளம்',
    welcomeBack: 'மீண்டும் நல்வரவு',
    earningsThisMonth: 'இந்த மாத வருமானம்',
    activeOrders: 'செயலில் உள்ள ஆர்டர்கள்',
    lowStockAlert: 'குறைந்த இருப்பு எச்சரிக்கை',
    quickActions: 'விரைவு செயல்கள்',
    addProduct: 'பொருளைச் சேர்',
    updatePrice: 'விலை மாற்றம்',
    updateStock: 'இருப்பு மாற்றம்',
    viewOrders: 'ஆர்டர்களைப் பார்',
    myProducts: 'என் விளைபொருட்கள்',
    stockStatus: 'இருப்பு நிலை',
    currentPrice: 'தற்போதைய விலை',
    editPrice: 'விலை திருத்து',
    inStock: 'இருப்பில் உள்ளது',
    lowStock: 'குறைந்த இருப்பு',
    outOfStock: 'தீர்ந்துவிட்டது',
    aiPriceHint: 'AI பரிந்துரை ₹{price}',
    login: 'உள்நுழைக',
    register: 'பதிவு செய்க',
    phoneOrEmail: 'தொலைபேசி எண் அல்லது மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    otp: 'OTP (டெமோ குறியீடு 1234)',
    sendOtp: 'OTP அனுப்பு',
    verifyLogin: 'சரிபார்த்து உள்நுழைக',
    continueWithGoogle: 'Google மூலம் தொடரவும்',
    orSignInWith: 'அல்லது உள்நுழைக',
    rememberMe: 'என்னை நினைவில் வை',
    forgotPassword: 'கடவுச்சொல் மறந்துவிட்டீர்களா?',
    sendResetLink: 'மீட்டமைப்பு இணைப்பு அனுப்பு',
    resetLinkSent: 'உங்கள் மின்னஞ்சலைப் பரிசோதிக்கவும்',
    resetLinkSentDesc: 'அந்த மின்னஞ்சல் முகவரியில் கணக்கு இருந்தால், மீட்டமைப்பு இணைப்பை அனுப்பியுள்ளோம்.',
    backToLogin: 'உள்நுழைவுக்கு திரும்பு',
    enterEmailForReset: 'உங்கள் மின்னஞ்சல் முகவரியை உள்ளிடவும்.',
    newPassword: 'புதிய கடவுச்சொல்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    resetPassword: 'கடவுச்சொல்லை மீட்டமை',
    passwordStrengthWeak: 'மிகவும் பலவீனம்',
    passwordStrengthFair: 'சாதாரணம்',
    passwordStrengthGood: 'நல்லது',
    passwordStrengthStrong: 'வலுவானது',
    passwordsDoNotMatch: 'கடவுச்சொற்கள் பொருந்தவில்லை',
    passwordTooShort: 'குறைந்தது 8 எழுத்துக்கள் இருக்க வேண்டும்',
    passwordResetSuccess: 'கடவுச்சொல் மீட்டமைக்கப்பட்டது!',
    invalidResetToken: 'இந்த இணைப்பு செல்லாதது அல்லது காலாவதியானது.',
    resendOtp: 'OTP மீண்டும் அனுப்பு',
    resendIn: 'மீண்டும் அனுப்பு',
    otpAutoAdvance: 'ஒவ்வொரு பெட்டியிலும் ஒரு இலக்கம்',
    mobileNumber: 'கைபேசி எண்',
    invalidMobile: 'சரியான 10 இலக்க கைபேசி எண்ணை உள்ளிடவும்',
    googleAuthOnly: 'இந்த கணக்கு Google மூலம் உள்நுழைகிறது.',
    googleRoleMismatch: 'இந்த Google கணக்கு வேறொரு பங்கில் பதிவு செய்யப்பட்டுள்ளது.',
    completeProfile: 'உங்கள் சுயவிவரத்தை நிறைவு செய்யுங்கள்',
    completeProfileDesc: 'தொடங்குவதற்கு சில விவரங்கள் மட்டும்.',
    completeProfileSave: 'சேமி & டாஷ்போர்டுக்கு செல்',
    farmName: 'பண்ணை / கிராம பெயர்',
    farmLocation: 'மாவட்டம் & மாநிலம்',
    deliveryAddress: 'டெலிவரி முகவரி',
    vehicleNumber: 'வாகன பதிவு எண்',
    farmerLoginHeadline: 'நேரடியாக விற்கவும். அதிக வருமானம் பெறவும்.',
    farmerLoginSubline: 'உங்கள் விளைபொருட்களை பட்டியலிட்டு, சொந்த விலை நிர்ணயித்து, இடைத்தரகர் இல்லாமல் வாடிக்கையாளர்களை அடையுங்கள்.',
    customerLoginHeadline: 'பண்ணையிலிருந்து நேரடியாக உங்கள் வீட்டிற்கு.',
    customerLoginSubline: 'உண்மையான விவசாயிகளிடமிருந்து உண்மையான விளைபொருட்கள் — இடைத்தரகர் இல்லை, கூடுதல் விலை இல்லை.',
    deliveryLoginHeadline: 'இறுதி மைல் டெலிவரி செய்யுங்கள்.',
    deliveryLoginSubline: 'பண்ணைகளில் பொருட்களை பெற்று, புதியதாக வழங்கி, சரியான நேரத்தில் ஊதியம் பெறுங்கள்.',
    trustFarmers: '500+ விவசாயிகள்',
    trustMiddlemen: 'இடைத்தரகர் இல்லை',
    trustFresh: '24 மணி நேரத்தில் புதியது',
    authErrorIncorrect: 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்.',
    authErrorGeneric: 'ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    signingIn: 'உள்நுழைகிறது…',
    sending: 'அனுப்புகிறது…',
    resetting: 'மீட்டமைக்கிறது…',
    saving: 'சேமிக்கிறது…',
    searchPlaceholder: 'காய்கறிகள், பழங்கள், தானியங்களைத் தேடுங்கள்...',
    addToCart: 'கூடையில் சேர்',
    onDuty: 'பணியில் உள்ளார்',
    offDuty: 'விடுப்பில் உள்ளார்',
    totalDeliveries: 'இன்றைய மொத்த டெலிவரிகள்',
    completedSoFar: 'முடிக்கப்பட்டவை',
    pickup: 'பெறும் இடம்',
    drop: 'வழங்கும் இடம்',
    acceptJob: 'டெலிவரியை ஏற்றுக்கொள்',
    markPickedUp: 'பொருளைப் பெற்றேன்',
    outForDelivery: 'டெலிவரிக்கு புறப்பட்டது',
    markDelivered: 'டெலிவரி முடிந்தது',
    upcomingJobs: 'அடுத்த டெலிவரிகள்',
    home: 'முகப்பு',
    route: 'வழித்தடம்',
    history: 'வரலாறு',
    profile: 'சுயவிவரம்',
    // Analytics
    analytics: 'பகுப்பாய்வு',
    analyticsTitle: 'விவசாயி விற்பனை & வருமான பகுப்பாய்வு',
    analyticsSubtitle: 'உங்கள் உண்மையான விற்பனை போக்கு மற்றும் அறுவடை விவரங்கள்',
    totalRevenue: 'மொத்த வாழ்நாள் வருமானம்',
    totalOrders: 'மொத்த ஆர்டர்கள்',
    unitsSold: 'விற்பனையான அளவுகள்',
    avgOrderValue: 'சராசரி ஆர்டர் மதிப்பு',
    revenueTrend: 'வருமான வரைபடம்',
    topProducts: 'அதிகம் விற்ற விளைபொருட்கள்',
    categorySplit: 'பிரிவு வாரியான விற்பனை',
    inventoryHealth: 'இருப்பு ஆரோக்கியம்',
    noSalesYet: 'விற்பனை விவரங்கள் எதுவும் இல்லை — புதிய ஆர்டர்கள் கிடைத்தவுடன் இங்கு காண்பிக்கப்படும்.',
    days7: '7 நாட்கள்',
    days30: '30 நாட்கள்',
    months6: '6 மாதங்கள்',
    // AI Assistant
    aiAssistant: 'AI உதவியாளர்',
    aiAssistantTitle: 'Farm2Home AI பண்ணை உதவியாளர்',
    aiAssistantSubtitle: 'நேரடி சந்தை விலை நிர்ணயம் மற்றும் இருப்பு ஆலோசனை',
    typeMessagePlaceholder: 'கேள்வி கேட்கவும் (எ.கா: எந்த விளைபொருட்கள் இருப்பு குறைவாக உள்ளது?)...',
    assistantTyping: 'AI உதவியாளர் பதிலளிக்கிறார்...',
    promptLowStock: 'எந்த விளைபொருட்கள் இருப்பு குறைவாக உள்ளது?',
    promptPriceHelp: 'விலையை எவ்வாறு மாற்றுவது?',
    promptBestSeller: 'சமீபத்தில் அதிகம் விற்பனையானது எது?',
    promptOrders: 'சமீபத்திய ஆர்டர்களைக் காட்டு',
    aiError: 'உதவியாளரைத் தொடர்பு கொள்ள முடியவில்லை — மீண்டும் முயற்சிக்கவும்.',
    applyAiAction: 'பரிந்துரையை ஏற்றுக்கொள்',
    // Earnings & Payouts
    earnings: 'வருமானம்',
    earningsTitle: 'விவசாயி வருமானம் & பணப்பரிவர்த்தனைகள்',
    earningsSubtitle: 'நேரடி வங்கி பரிமாற்றம் மற்றும் ஆர்டர் வரவு விவரங்கள்',
    lifetimeEarnings: 'மொத்த வாழ்நாள் வருமானம்',
    pendingBalance: 'நிலுவை தொகை',
    paidOutAmount: 'பெறப்பட்ட தொகை',
    requestPayout: 'பணம் பெறக் கோரிக்கை',
    payoutDestination: 'பணம் பெறும் கணக்கு',
    editDestination: 'விவரங்களை மாற்று',
    minPayoutNotice: 'குறைந்தபட்ச பணப்பரிவர்த்தனை கோரிக்கை ₹500',
    transactionsTitle: 'வருமான பரிவர்த்தனை பட்டியல் (ஆர்டர்கள்)',
    orderNumber: 'ஆர்டர் #',
    date: 'தேதி',
    customer: 'வாடிக்கையாளர்',
    items: 'பொருட்கள்',
    gross: 'மொத்த தொகை',
    platformFee: 'தள கட்டணம் (0%)',
    net: 'நிகர வரவு',
    status: 'நிலை',
    filterAll: 'அனைத்து நிலைகளும்',
    filterPending: 'நிலுவையில் உள்ளவை',
    filterPaid: 'பரிமாற்றம் செய்யப்பட்டது',
    payoutHistory: 'பணப்பரிமாற்ற வரலாறு',
    noTransactionsYet: 'பரிவர்த்தனைகள் எதுவும் இல்லை. ஆர்டர்கள் வந்தவுடன் இங்கு தோன்றும்.'
  },
  hi: {
    appTitle: 'Farm2Home (फार्म2होम)',
    tagline: 'सीधे किसानों से ताज़ा उपज आपके घर तक',
    selectRole: 'जारी रखने के लिए अपनी भूमिका चुनें',
    farmerRole: 'किसान',
    farmerDesc: 'बिचौलियों के बिना अपनी उपज सीधे उचित मूल्य पर बेचें।',
    customerRole: 'ग्राहक',
    customerDesc: 'खेत से सीधे ताज़ी सब्जियां और फल मंगवाएं।',
    deliveryRole: 'डिलीवरी एजेंट',
    deliveryDesc: 'आस-पास के डिलीवरी ऑर्डर स्वीकार करें और कमाई करें।',
    adminPortal: 'एडमिन पोर्टल',
    welcomeBack: 'स्वागत है',
    earningsThisMonth: 'इस महीने की कमाई',
    activeOrders: 'सक्रिय ऑर्डर',
    lowStockAlert: 'कम स्टॉक चेतावनी',
    quickActions: 'त्वरित कार्य',
    addProduct: 'उत्पाद जोड़ें',
    updatePrice: 'मूल्य बदलें',
    updateStock: 'स्टॉक बदलें',
    viewOrders: 'ऑर्डर देखें',
    myProducts: 'मेरे उत्पाद',
    stockStatus: 'स्टॉक स्थिति',
    currentPrice: 'वर्तमान मूल्य',
    editPrice: 'मूल्य बदलें',
    inStock: 'स्टॉक में उपलब्ध',
    lowStock: 'कम स्टॉक',
    outOfStock: 'स्टॉक समाप्त',
    aiPriceHint: 'AI सुझाव ₹{price}',
    login: 'लॉग इन करें',
    register: 'पंजीकरण करें',
    phoneOrEmail: 'फ़ोन नंबर या ईमेल',
    password: 'पासवर्ड',
    otp: 'ओटीपी (डेमो 1234)',
    sendOtp: 'ओटीपी भेजें',
    verifyLogin: 'लॉग इन करें',
    continueWithGoogle: 'Google से जारी रखें',
    orSignInWith: 'या लॉग इन करें',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    sendResetLink: 'रीसेट लिंक भेजें',
    resetLinkSent: 'अपना ईमेल जाँचें',
    resetLinkSentDesc: 'यदि उस ईमेल पर कोई खाता है, तो हमने पासवर्ड रीसेट लिंक भेज दिया है।',
    backToLogin: 'लॉग इन पर वापस जाएं',
    enterEmailForReset: 'अपना ईमेल पता दर्ज करें और हम आपको रीसेट लिंक भेजेंगे।',
    newPassword: 'नया पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    resetPassword: 'पासवर्ड रीसेट करें',
    passwordStrengthWeak: 'कमज़ोर',
    passwordStrengthFair: 'ठीक',
    passwordStrengthGood: 'अच्छा',
    passwordStrengthStrong: 'मज़बूत',
    passwordsDoNotMatch: 'पासवर्ड मेल नहीं खाते',
    passwordTooShort: 'पासवर्ड कम से कम 8 अक्षरों का होना चाहिए',
    passwordResetSuccess: 'पासवर्ड रीसेट हो गया! अब आप नए पासवर्ड से लॉग इन कर सकते हैं।',
    invalidResetToken: 'यह रीसेट लिंक अमान्य या समाप्त हो गया है।',
    resendOtp: 'OTP दोबारा भेजें',
    resendIn: 'दोबारा भेजें',
    otpAutoAdvance: 'प्रत्येक बॉक्स में एक अंक',
    mobileNumber: 'मोबाइल नंबर',
    invalidMobile: 'वैध 10 अंकों का मोबाइल नंबर दर्ज करें',
    googleAuthOnly: 'यह खाता Google Sign-in का उपयोग करता है।',
    googleRoleMismatch: 'यह Google खाता एक अलग भूमिका के साथ पंजीकृत है।',
    completeProfile: 'अपनी प्रोफ़ाइल पूरी करें',
    completeProfileDesc: 'शुरू करने के लिए बस कुछ और विवरण।',
    completeProfileSave: 'सहेजें और डैशबोर्ड पर जाएं',
    farmName: 'खेत / गाँव का नाम',
    farmLocation: 'जिला और राज्य',
    deliveryAddress: 'डिलीवरी पता',
    vehicleNumber: 'वाहन पंजीकरण संख्या',
    farmerLoginHeadline: 'सीधे बेचें। अधिक कमाएं।',
    farmerLoginSubline: 'अपनी उपज सूचीबद्ध करें, अपनी कीमत तय करें, बिचौलियों के बिना ग्राहकों तक पहुँचें।',
    customerLoginHeadline: 'खेत से सीधे आपके घर तक।',
    customerLoginSubline: 'असली किसानों से असली उपज — कोई बिचौलिया नहीं, कोई अतिरिक्त शुल्क नहीं।',
    deliveryLoginHeadline: 'अंतिम मील डिलीवरी करें।',
    deliveryLoginSubline: 'खेतों से सामान उठाएं, ताज़ा डिलीवर करें, समय पर भुगतान पाएं।',
    trustFarmers: '500+ किसान',
    trustMiddlemen: 'शून्य बिचौलिया',
    trustFresh: '24 घंटे में ताज़ा',
    authErrorIncorrect: 'गलत ईमेल या पासवर्ड। कृपया पुनः प्रयास करें।',
    authErrorGeneric: 'कुछ गलत हुआ। कृपया पुनः प्रयास करें।',
    emailAddress: 'ईमेल पता',
    signingIn: 'लॉग इन हो रहा है…',
    sending: 'भेजा जा रहा है…',
    resetting: 'रीसेट हो रहा है…',
    saving: 'सहेजा जा रहा है…',
    searchPlaceholder: 'सब्जियां, फल, अनाज या किसान खोजें...',
    addToCart: 'कार्ट में जोड़ें',
    onDuty: 'ड्यूटी पर',
    offDuty: 'छुट्टी पर',
    totalDeliveries: 'आज की कुल डिलीवरी',
    completedSoFar: 'पूरी हुई डिलीवरी',
    pickup: 'पिकअप',
    drop: 'ड्रॉप',
    acceptJob: 'डिलीवरी स्वीकार करें',
    markPickedUp: 'सामान उठाया',
    outForDelivery: 'डिलीवरी के लिए रवाना',
    markDelivered: 'डिलीवरी पूरी हुई',
    upcomingJobs: 'आगामी डिलीवरी',
    home: 'होम',
    route: 'रूट',
    history: 'इतिहास',
    profile: 'प्रोफ़ाइल',
    // Analytics
    analytics: 'एनालिटिक्स',
    analyticsTitle: 'किसान बिक्री एवं राजस्व विश्लेषण',
    analyticsSubtitle: 'अपनी वास्तविक बिक्री और उपज प्रदर्शन पर नज़र रखें',
    totalRevenue: 'कुल आजीवन राजस्व',
    totalOrders: 'कुल ऑर्डर',
    unitsSold: 'कुल बेची गई मात्रा',
    avgOrderValue: 'औसत ऑर्डर मूल्य',
    revenueTrend: 'राजस्व रुझान',
    topProducts: 'शीर्ष बिकने वाले उत्पाद',
    categorySplit: 'श्रेणीवार वितरण',
    inventoryHealth: 'स्टॉक स्थिति',
    noSalesYet: 'अभी कोई बिक्री डेटा नहीं है — ऑर्डर मिलने पर आपका विश्लेषण यहां दिखाई देगा।',
    days7: '7 दिन',
    days30: '30 दिन',
    months6: '6 महीने',
    // AI Assistant
    aiAssistant: 'AI सहायक',
    aiAssistantTitle: 'Farm2Home AI किसान सहायक',
    aiAssistantSubtitle: 'बाज़ार मूल्य सुझाव, स्टॉक जांच और बहुभाषी सहायता',
    typeMessagePlaceholder: 'सवाल पूछें (उदा: कौन से उत्पाद कम स्टॉक में हैं?)...',
    assistantTyping: 'सहायक उत्तर तैयार कर रहा है...',
    promptLowStock: 'कौन से उत्पाद कम स्टॉक में हैं?',
    promptPriceHelp: 'मैं अपना मूल्य कैसे बदलूँ?',
    promptBestSeller: 'हाल ही में सबसे ज्यादा क्या बिका?',
    promptOrders: 'मेरे हाल के ऑर्डर दिखाएं',
    aiError: 'सहायक से संपर्क नहीं हो सका — कृपया पुनः प्रयास करें।',
    applyAiAction: 'सुझाव लागू करें',
    // Earnings & Payouts
    earnings: 'कमाई',
    earningsTitle: 'किसान कमाई एवं भुगतान',
    earningsSubtitle: 'सीधा बैंक खाता निपटान और लेनदेन रिकॉर्ड',
    lifetimeEarnings: 'कुल आजीवन कमाई',
    pendingBalance: 'बकाया राशि',
    paidOutAmount: 'प्राप्त की गई राशि',
    requestPayout: 'भुगतान का अनुरोध करें',
    payoutDestination: 'भुगतान खाता',
    editDestination: 'विवरण बदलें',
    minPayoutNotice: 'न्यूनतम भुगतान अनुरोध ₹500 है',
    transactionsTitle: 'कमाई बहीखाता (ऑर्डर लेनदेन)',
    orderNumber: 'ऑर्डर #',
    date: 'तारीख',
    customer: 'ग्राहक',
    items: 'उत्पाद',
    gross: 'कुल राशि',
    platformFee: 'प्लेटफ़ॉर्म शुल्क (0%)',
    net: 'शुद्ध भुगतान',
    status: 'स्थिति',
    filterAll: 'सभी स्थितियां',
    filterPending: 'लंबित निपटान',
    filterPaid: 'भुगतान संपन्न',
    payoutHistory: 'भुगतान इतिहास',
    noTransactionsYet: 'अभी कोई लेनदेन नहीं है। नए ऑर्डर यहां स्वतः दिखाई देंगे।'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('farm2home_lang') || 'en');

  useEffect(() => {
    localStorage.setItem('farm2home_lang', lang);
  }, [lang]);

  const t = (key, params = {}) => {
    let text = (translations[lang] && translations[lang][key]) || translations.en[key] || key;
    Object.keys(params).forEach(param => {
      text = text.replace(`{${param}}`, params[param]);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
